In [8]:
import numpy as np

In [12]:
def g_j_inverse(mat_orig):
    
    mat = np.copy(mat_orig)
    
    n = mat.shape[0]
    
    if (mat.shape[1] != n):
        
        return -1
    
    b_mat = np.identity(n)
    
    # For each row i
    for i in range(n):
        
        # Eliminate each row j
        for j in range(n):
            
            if (i != j):  
                        
                frac = mat[j,i]/mat[i,i]
            
                mat[j,:] = mat[j,:] - frac*mat[i,:]
                
                b_mat[j,:] = b_mat[j,:] - frac*b_mat[i,:]
                
        
    for i in range(n):
    
        b_mat[i,:] = b_mat[i,:]/mat[i,i]
        mat[i,:] = mat[i,:]/mat[i,i]
                    
    return b_mat

In [21]:
mat = np.random.uniform(2,3,size=(4,4))

inv = g_j_inverse(mat)

print(inv @ mat)

[[ 1.00000000e+00 -2.20708982e-15 -2.04485962e-15 -4.27034634e-15]
 [-3.67424540e-15  1.00000000e+00 -4.60256563e-15 -2.65994575e-15]
 [-7.27817516e-16 -9.28467336e-16  1.00000000e+00 -2.26643553e-16]
 [ 1.87517497e-16 -1.45810536e-16 -2.39818313e-16  1.00000000e+00]]


In [22]:
def pseudoinverse(mat):
    
    return mat.T @ g_j_inverse(mat @ mat.T)